import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/global.css";
import Navigation from "@/components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
      template : "%s | Next js",
      default : "Test Title",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navigation />
      {children}
      </body>
    </html>
  );
}
